### ISSUE TITLE
Failing assertions for Signature.cryptsl

### ISSUE THREAD

**Issue by rakshitkr** [CROSSINGTUD/CryptoAnalysis#115]
The below test case is failing since the `Signature` object `s` is going to error state

```
@Test
	public void testSignature() throws InvalidKeyException, GeneralSecurityException {
		Signature s = Signature.getInstance("SHA256withRSA");
//		no initSign call
		s.update(tData);
		s.sign();
		Assertions.notHasEnsuredPredicate(s); // passing
		Assertions.mustNotBeInAcceptingState(s); // failing
//		Assertions.mustBeInAcceptingState(s); // also failing
	}
```

**Comment by kruegers** [comment]
Just to be clear, it fails for both mustBeInAcceptingState *and* mustnotBeInAcceptingState?

**Comment by rakshitkr** [comment]
Yes @kruegers

**Comment by kruegers** [comment]
Can you please post the two error messages here?

**Comment by rakshitkr** [comment]
java.lang.RuntimeException: Unsound results: 
[s (SignatureTest.testSignature)@staticinvoke <test.assertions.Assertions: void mustNotBeInAcceptingState(java.lang.Object)>(s) must not be in error state]
	at test.UsagePatternTestingFramework$1.internalTransform(UsagePatternTestingFramework.java:345)
	at soot.SceneTransformer.transform(SceneTransformer.java:36)
	at soot.Transform.apply(Transform.java:102)
	at soot.ScenePack.internalApply(ScenePack.java:35)
	at soot.Pack.apply(Pack.java:117)
	at test.core.selfrunning.AbstractTestingFramework.analyze(AbstractTestingFramework.java:78)
	at test.core.selfrunning.AbstractTestingFramework.beforeTestCaseExecution(AbstractTestingFramework.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

**Comment by rakshitkr** [comment]
java.lang.RuntimeException: Unsound results: 
[s (SignatureTest.testSignature)@staticinvoke <test.assertions.Assertions: void mustBeInAcceptingState(java.lang.Object)>(s) must not be in error state]
	at test.UsagePatternTestingFramework$1.internalTransform(UsagePatternTestingFramework.java:345)
	at soot.SceneTransformer.transform(SceneTransformer.java:36)
	at soot.Transform.apply(Transform.java:102)
	at soot.ScenePack.internalApply(ScenePack.java:35)
	at soot.Pack.apply(Pack.java:117)
	at test.core.selfrunning.AbstractTestingFramework.analyze(AbstractTestingFramework.java:78)
	at test.core.selfrunning.AbstractTestingFramework.beforeTestCaseExecution(AbstractTestingFramework.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

**Comment by rakshitkr** [comment]
I even verified if the corresponding `.cryptslbin` file is in the test/resources folder

**Comment by kruegers** [comment]
Thanks. 
The error message for mustBeInAcceptingState seems wrong to me. What do you think, @johspaeth?

**Comment by johspaeth** [comment]
The solution introduces non-deterministic results

**Comment by johspaeth** [comment]
I !hope! the non-determinism is solved, I run the test cases more then 10 times and the CI did not fail anymore.
