### ISSUE TITLE
JNI error, NoClassDefFoundError: org/apache/commons/cli/Options

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/CryptoAnalysis#217]
After I check out the code and perform a clean build:

``mvn clean package -DskipTests``

 (ignoring test as some are failing!)

I receive a JNI error when using the command provided in the readme, 

`java -cp target/CryptoAnalysis-2.7-SNAPSHOT.jar crypto.HeadlessCryptoScanner ...`

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/Options
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.Options
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more

```

**Comment by johspaeth** [comment]
Used the wrong `.jar` (without dependencies) from `target` and not from `build`
