### ISSUE TITLE
CSV Export not working

### ISSUE THREAD

**Issue by luismoeller** [CROSSINGTUD/CryptoAnalysis#368]
When executed with the `--csvReportFile` flag set, a null pointer exception occurs. Without the flag everything workes as expected.

```
~ $ java -cp CryptoAnalysis-2.7.1-SNAPSHOT-jar-with-dependencies.jar crypto.HeadlessCryptoScanner --rulesDir /home/app/src/  --applicationCp /home/app/Examples.jar --reportDir testcsv/ --csvReportFile test.csv

[main] INFO crypto.HeadlessCryptoScanner - Using call graph algorithm CHA
[main] INFO crypto.HeadlessCryptoScanner - Analysis soot setup done in 593.9 ms 
Exception in thread "main" java.lang.NullPointerException
	at crypto.reporting.CSVReporter.put(CSVReporter.java:188)
	at crypto.reporting.CSVReporter.put(CSVReporter.java:192)
	at crypto.reporting.CSVReporter.<init>(CSVReporter.java:89)
	at crypto.HeadlessCryptoScanner$3.internalTransform(HeadlessCryptoScanner.java:258)
	at soot.SceneTransformer.transform(SceneTransformer.java:36)
	at soot.Transform.apply(Transform.java:102)
	at soot.ScenePack.internalApply(ScenePack.java:35)
	at soot.Pack.apply(Pack.java:117)
	at crypto.HeadlessCryptoScanner.analyse(HeadlessCryptoScanner.java:199)
	at crypto.HeadlessCryptoScanner.exec(HeadlessCryptoScanner.java:167)
	at crypto.HeadlessCryptoScanner.main(HeadlessCryptoScanner.java:72)
```

**Comment by Projucti** [comment]
Unfortunately, CryptoAnalysis doesn't take ` --csvReportFile` or` --reportDir` tag as arguments. Please follow the provided guideline for running CryptoAnalysis. Instead of the above command, you may try this one: 

` ~ $ java -cp CryptoAnalysis-2.7.1-SNAPSHOT-jar-with-dependencies.jar crypto.HeadlessCryptoScanner --rulesDir/home/app/src/  --applicationCp /home/app/Examples.jar --reportPath C:\Users\reports  --reportFormat CSV`

You may use other additional arguments as follows:

```
--cg <selection_of_call_graph_for_analysis> (possible values are CHA, SPARK, SPARKLIB)
--sootPath <absolute_path_of_whole_project>
--identifier <identifier_for_labelling_output_files>
--preanalysis (enables pre-analysis)
--visualization (enables the visualization, but also requires --reportPath option to be set)
--providerDetection (enables provider detection analysis)
```

**Comment by luismoeller** [comment]
I tried this before, but the `--reportPath` option doesn't work as expected.

```
~ $ java -cp CryptoAnalysis-2.7.1-SNAPSHOT-jar-with-dependencies.jar crypto.HeadlessCryptoScanner --rulesDir /home/app/src/ --applicationCp /home/app/data/test.jar --
reportPath /home/app/data/ --reportFormat CSV
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --reportPath
	at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360)
	at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:407)
	at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:384)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:239)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
	at crypto.HeadlessCryptoScanner.createFromOptions(HeadlessCryptoScanner.java:77)
	at crypto.HeadlessCryptoScanner.main(HeadlessCryptoScanner.java:71)
```

**Comment by Projucti** [comment]
CryptoAnalysis-2.7.1-SNAPSHOT doesn't recognize the above arguments. There have been significant changes with the project and it's arguments. Please try with the latest version of the CryptoAnalysis.

**Comment by AnakinSklavenwalker** [comment]
@Projucti do you referr to CryptoAnalysis 2.7.2 which is stable or shall @luismoeller use the beta builds? 
Also could you please look into fixing this for a 2.7.3 release? I think this sounds rather important to have reporting fixed in a stable release.

**Comment by Projucti** [comment]
I completely agree with you as CryptoAnalysis-2.7.2 stable version has same issue. For now, I am suggesting @luismoeller to use the latest beta builds CryptoAnalysis-2.8.0-SNAPSHOT. I am looking into fixing this for next stable release.

**Comment by Maximilianhummel** [comment]
currently, I am facing the same issue as @luismoeller. I tried to build the latest version from the develop branch as recommended from @Projucti  with some errors. Git also indicates that the current version is failing in building. Is there already a possible workaround or even a solution for this?

**Comment by Projucti** [comment]
@Maximilianhummel unfortunately, CSV reporting is working correctly with the develop branch from my side. Can you please provide more details/ files/steps which are causing the error so that I can recreate/reproduce the issue from my side?

**Comment by Maximilianhummel** [comment]
Thanks for the quick reply! the build ist now working. the groupId was missing for apache maven plugins.

`<plugin>
                **<groupId>org.apache.maven.plugins</groupId>**
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>`

**Comment by Projucti** [comment]
Thanks for pointing out that! I have added this now and all the changes are going to be added on the new stable release hopefully.
