### ISSUE TITLE
CogniCrypt for android soot error

### ISSUE THREAD

**Issue by iheming** [CROSSINGTUD/CryptoAnalysis#492]
when running the cognicrypt for android, after running the class, there is a error about soot, so how to fix it?
the error is as follow,
[main] INFO de.fraunhofer.iem.crypto.CogniCryptAndroidAnalysis - Running static analysis on APK file CryptoAnalysis-master/APP/test_game.apk
[main] INFO de.fraunhofer.iem.crypto.CogniCryptAndroidAnalysis - with Android Platforms dir Android/Sdk/platforms
[main] INFO de.fraunhofer.iem.crypto.CogniCryptAndroidAnalysis - Constructing call graph
[main] INFO soot.jimple.infoflow.android.SetupApplication - Initializing Soot...
[main] INFO soot.jimple.infoflow.android.SetupApplication - Loading dex files...
Exception in thread "main" java.lang.NoSuchMethodError: 'soot.LocalGenerator soot.Scene.createLocalGenerator(soot.Body)'
	at soot.jimple.infoflow.cfg.LibraryClassPatcher.generateMessageObtainMethod(LibraryClassPatcher.java:231)
	at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchMessageObtainImplementation(LibraryClassPatcher.java:123)
	at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchLibraries(LibraryClassPatcher.java:71)
	at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1220)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1504)
	at soot.jimple.infoflow.android.SetupApplication.constructCallgraph(SetupApplication.java:1376)
	at de.fraunhofer.iem.crypto.CogniCryptAndroidAnalysis.constructCallGraph(CogniCryptAndroidAnalysis.java:104)
	at de.fraunhofer.iem.crypto.CogniCryptAndroidAnalysis.run(CogniCryptAndroidAnalysis.java:67)
	at de.fraunhofer.iem.crypto.CogniCryptAndroidAnalysis.main(CogniCryptAndroidAnalysis.java:40)

**Comment by WulaBeryl** [comment]
I'm facing the same issue. How did you solve the problem?
